# docker-compose.yml
version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mycontacts
    ports:
      - 8000:8000

  redis:
    image: redis:alpine
    volumes:
      - .:/mycontacts
    ports:
      - 9001:6379
